#!/usr/bin/python
import argparse, sys, steamcmd, color, games

printc = color.printc
printcln = color.printcln

# Parse arguments
parser = argparse.ArgumentParser(description='Make SteamCMD easier to use.')
parser.add_argument('--list', dest='list', action='store_false', help='List all known games (app argument not required)')
parser.add_argument('--validate', dest='validate', action='store_false', help='Validate the game files')
parser.add_argument('app', nargs='*', help='Application id, name, or abreviation (not required if --list used)')
args = parser.parse_args()

games_data = games.load_file("games.json")

# List all games in the data file
if not(args.list):
	for game in games_data['games']:
		printcln(game['name'] + ' (' + str(game['app_id']) + ')')
		printcln('Aliases:')
		for alias in game['aliases']:
			printcln('- ' + alias)
		printcln("")
	sys.exit(0)

# Not listing... Do we have an app then?
if len(args.app) == 0:
	parser.print_help()
	sys.exit(1)

# We have an app, find and install it!
print args.app
