#!/usr/bin/python
import argparse, sys, steamcmd, color, games, config

printc = color.printc
printcln = color.printcln

# Parse arguments
parser = argparse.ArgumentParser(description='Make SteamCMD easier to use.')
parser.add_argument('--list', dest='list', action='store_true', help='List all known games (app argument not required)')
parser.add_argument('--validate', dest='validate', action='store_true', help='Validate the game files')
parser.add_argument('app', nargs='*', help='Application id, name, or abreviation (not required if --list used)')
args = parser.parse_args()

# Not listing and no app? Show help
if not(args.list) and len(args.app) == 0:
	parser.print_help()
	sys.exit(1)

games_data = games.load_file(config.AUTOSTEAMCMD_PATH + "/games.json")

# List all games in the data file
if args.list:
	name_width = max(len(row['name']) for row in games_data['games']) # Padding for name
	printcln("Name:".ljust(name_width) + '    ' + "App ID:".ljust(10) + '    ' + "Aliases:")
	for game in games_data['games']:
		printcln(game['name'].ljust(name_width) + '    ' + str(game['app_id']).ljust(10) + '    ' + "".join(alias + ' ' for alias in game['aliases']))
	sys.exit(0)

# We have an app, find and install it!
print args.app
